// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pobeda.DAL.Data;

#nullable disable

namespace Pobeda.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240521102539_RemoveAllAndInitialize")]
    partial class RemoveAllAndInitialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartProduct", b =>
                {
                    b.Property<int>("CartsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CartsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CartProduct");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TranslitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "\\img\\category\\category-telefony.png",
                            Name = "Телефоны",
                            TranslitName = "telefony"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "\\img\\category\\category-kompyuternaya-tehnika.png",
                            Name = "Компьютерная техника",
                            TranslitName = "kompyuternaya-tehnika"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "\\img\\category\\category-instrument.png",
                            Name = "Инструмент",
                            TranslitName = "instrument"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "\\img\\category\\category-igry-i-pristavki.png",
                            Name = "Игры и приставки",
                            TranslitName = "igry-i-pristavki"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "\\img\\category\\category-tovary-dlya-doma.png",
                            Name = "Товары для дома",
                            TranslitName = "tovary-dlya-doma"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "\\img\\category\\category-avto.png",
                            Name = "Авто",
                            TranslitName = "avto"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "\\img\\category\\category-foto-i-videotehnika.png",
                            Name = "Фото и видеотехника",
                            TranslitName = "foto-i-videotehnika"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "\\img\\category\\category-hobbi-i-otdyh.png",
                            Name = "Хобби и отдых",
                            TranslitName = "hobbi-i-otdyh"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "\\img\\category\\category-lichnye-vecshi.png",
                            Name = "Личные вещи",
                            TranslitName = "lichnye-vecshi"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "\\img\\category\\category-audiotehnika.png",
                            Name = "Аудиотехника",
                            TranslitName = "audiotehnika"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "\\img\\category\\category-tv-i-video.png",
                            Name = "ТВ и видео",
                            TranslitName = "tv-i-video"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "\\img\\category\\category-tovary-dlya-detei.png",
                            Name = "Товары для детей",
                            TranslitName = "tovary-dlya-detei"
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.CategoryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Iphone 15"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Iphone 13"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Samsung S22"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Samsung S21"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Href = "/catalog/telefony/naushniki-dlya-telefonov/",
                            Name = "Наушники"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Power bank"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Href = "#",
                            Name = "USB кабель"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Apple watch"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Href = "#",
                            Name = "AirPods"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Iphone 11"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Href = "#",
                            Name = "Iphone 14"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Href = "#",
                            Name = "Macbook"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Href = "#",
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Href = "#",
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Href = "#",
                            Name = "HP"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Href = "/catalog/kompyuternaya-tehnika/klaviatury/",
                            Name = "Клавиатуры"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Href = "/catalog/kompyuternaya-tehnika/jestkie-diski/",
                            Name = "Жесткий Диск"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Href = "/catalog/kompyuternaya-tehnika/printery-i-mfu/",
                            Name = "Принтер"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Href = "#",
                            Name = "УШМ"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Дрель"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Шуруповерт"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Пила"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Нивелир"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Сварочник"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Фрезер"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Лобзик"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Href = "#",
                            Name = "Набор инструментов"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Href = "#",
                            Name = "PS1"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Href = "#",
                            Name = "PS2"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Href = "#",
                            Name = "PS3"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Href = "#",
                            Name = "PS4"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Href = "#",
                            Name = "PS5"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Href = "#",
                            Name = "Джойстик"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Href = "#",
                            Name = "Робот пылесос"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            Href = "#",
                            Name = "Отпариватель"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 5,
                            Href = "#",
                            Name = "Обогреватель"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Href = "#",
                            Name = "Электроплита"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            Href = "#",
                            Name = "Мясорубка"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Href = "#",
                            Name = "Кофемолка"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Href = "#",
                            Name = "Соковыжималка"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 6,
                            Href = "#",
                            Name = "Сабвуфер"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            Href = "#",
                            Name = "Аптечка"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 6,
                            Href = "#",
                            Name = "Домкрат"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            Href = "/catalog/avto/radardetektory/",
                            Name = "Антирадар"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            Href = "#",
                            Name = "Компрессор"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            Href = "#",
                            Name = "Набор автомобилиста"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            Href = "#",
                            Name = "Сигнализация"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 7,
                            Href = "#",
                            Name = "Штатив"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 7,
                            Href = "#",
                            Name = "Вспышка"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 7,
                            Href = "#",
                            Name = "Объектив"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 8,
                            Href = "#",
                            Name = "Удочки"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 8,
                            Href = "#",
                            Name = "Велосипед"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 8,
                            Href = "#",
                            Name = "Гантели"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 8,
                            Href = "#",
                            Name = "Бинокль"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 8,
                            Href = "#",
                            Name = "Боксерские перчатки"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 8,
                            Href = "#",
                            Name = "Шлемы"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            Href = "#",
                            Name = "Для сноуборда"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Tissot"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Куртка"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Джинсы"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Кроссовки"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Сувениры"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Шуба"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Коллекционные фигурки"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Футболки"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 9,
                            Href = "#",
                            Name = "Casio"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 10,
                            Href = "#",
                            Name = "Колонка JBL"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 10,
                            Href = "#",
                            Name = "Ресивер"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 10,
                            Href = "#",
                            Name = "Микрофон"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 10,
                            Href = "/catalog/audiotehnika/muzykalnye-centry/",
                            Name = "Музыкальный центр"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 10,
                            Href = "#",
                            Name = "Яндекс станция"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 10,
                            Href = "#",
                            Name = "Синтезатор"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 10,
                            Href = "/catalog/audiotehnika/domashnie-kinoteatry/",
                            Name = "Домашний кинотеатр"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 11,
                            Href = "#",
                            Name = "Тв Samsung"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 11,
                            Href = "#",
                            Name = "Тв Dexp"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 11,
                            Href = "#",
                            Name = "Тв LG"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 11,
                            Href = "#",
                            Name = "Кронштейн для ТВ"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 11,
                            Href = "#",
                            Name = "Тв приставки"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 11,
                            Href = "#",
                            Name = "Проекторы"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 11,
                            Href = "#",
                            Name = "Провод HDMI"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 12,
                            Href = "/catalog/tovary-dlya-detei/detskie-avtokresla/",
                            Name = "Автокресла"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 12,
                            Href = "#",
                            Name = "Самокат детский"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 12,
                            Href = "#",
                            Name = "Велосипед детский"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 12,
                            Href = "#",
                            Name = "Коляски"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 12,
                            Href = "#",
                            Name = "Конструкторы"
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TranslitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            City = "Самара",
                            Description = "Состояние хорошее.",
                            ImageUrl = "\\products_image\\product_photo_1.webp",
                            Name = "Системный блок",
                            Price = 59000.0,
                            SubCategoryId = 8,
                            TranslitName = "sistemnyj-blok"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            City = "Саратов",
                            Description = "Состояние хорошее.",
                            ImageUrl = "\\products_image\\product_photo_2.webp",
                            Name = "Apple iPhone SE 128GB",
                            Price = 11900.0,
                            SubCategoryId = 1,
                            TranslitName = "apple-iphone-se-128gb"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            City = "Самара",
                            Description = "Состояние отличное.",
                            ImageUrl = "\\products_image\\product_photo_3.webp",
                            Name = "Apple iPhone 11 64GB",
                            Price = 29900.0,
                            SubCategoryId = 1,
                            TranslitName = "apple-iphone-11-64gb"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            City = "Саратов",
                            Description = "Состояние новый.",
                            ImageUrl = "\\products_image\\product_photo_4.webp",
                            Name = "Apple iPhone 12 128GB",
                            Price = 49900.0,
                            SubCategoryId = 1,
                            TranslitName = "apple-iphone-12-128gb"
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.ProductCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCharacteristics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "Объем оперативной памяти",
                            ProductId = 1,
                            Value = "32 ГБ"
                        },
                        new
                        {
                            Id = 2,
                            Key = "Тактовая частота процессора",
                            ProductId = 1,
                            Value = "2600 МГц"
                        },
                        new
                        {
                            Id = 3,
                            Key = "Количество ядер процессора",
                            ProductId = 1,
                            Value = "6"
                        },
                        new
                        {
                            Id = 4,
                            Key = "Тип оперативной памяти",
                            ProductId = 1,
                            Value = "DDR4"
                        },
                        new
                        {
                            Id = 5,
                            Key = "Диагональ",
                            ProductId = 2,
                            Value = "4 дюйм."
                        },
                        new
                        {
                            Id = 6,
                            Key = "Объем встроенной памяти",
                            ProductId = 2,
                            Value = "128 ГБ"
                        },
                        new
                        {
                            Id = 7,
                            Key = "Объем оперативной памяти",
                            ProductId = 2,
                            Value = "2 ГБ"
                        },
                        new
                        {
                            Id = 8,
                            Key = "Количество ядер процессора",
                            ProductId = 2,
                            Value = "2"
                        },
                        new
                        {
                            Id = 9,
                            Key = "Диагональ",
                            ProductId = 3,
                            Value = "6.1 дюйм."
                        },
                        new
                        {
                            Id = 10,
                            Key = "Объем встроенной памяти",
                            ProductId = 3,
                            Value = "64 ГБ"
                        },
                        new
                        {
                            Id = 11,
                            Key = "Объем оперативной памяти",
                            ProductId = 3,
                            Value = "4 ГБ"
                        },
                        new
                        {
                            Id = 12,
                            Key = "Количество ядер процессора",
                            ProductId = 3,
                            Value = "6"
                        },
                        new
                        {
                            Id = 13,
                            Key = "Диагональ",
                            ProductId = 4,
                            Value = "6.1 дюйм."
                        },
                        new
                        {
                            Id = 14,
                            Key = "Объем встроенной памяти",
                            ProductId = 4,
                            Value = "128 ГБ"
                        },
                        new
                        {
                            Id = 15,
                            Key = "Объем оперативной памяти",
                            ProductId = 4,
                            Value = "4 ГБ"
                        },
                        new
                        {
                            Id = 16,
                            Key = "Количество ядер процессора",
                            ProductId = 4,
                            Value = "6"
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В кредит"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Состояние новый"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Состояние хорошее"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Состояние отличное"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Состояние удовлетворительное"
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TranslitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Сотовые телефоны",
                            TranslitName = "sotovye-telefony"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Умные часы и браслеты",
                            TranslitName = "umnye-chasy-i-braslety"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Наушники для телефонов",
                            TranslitName = "naushniki-dlya-telefonov"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Рации",
                            TranslitName = "racii"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Зарядные устройства",
                            TranslitName = "zaryadnye-ustroistva"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Аксессуары для телефонов",
                            TranslitName = "aksessuary-dlya-telefonov"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Ноутбуки",
                            TranslitName = "noutbuki"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Системные блоки",
                            TranslitName = "sistemnye-bloki"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Мониторы",
                            TranslitName = "monitory"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Моноблоки",
                            TranslitName = "monobloki"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Компьютерные мыши",
                            TranslitName = "kompyuternye-myshi"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Клавиатуры",
                            TranslitName = "klaviatury"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Компьютерные гарнитуры и наушники",
                            TranslitName = "kompyuternye-garnitury-i-naushniki"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Web-камеры",
                            TranslitName = "webkamery"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Планшетные пк",
                            TranslitName = "planshetnye-pk"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Электронные книги",
                            TranslitName = "elektronnye-knigi"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Name = "Принтеры и МФУ",
                            TranslitName = "printery-i-mfu"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Name = "Роутеры и модемы",
                            TranslitName = "routery-i-modemy"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Name = "Жесткие диски",
                            TranslitName = "jestkie-diski"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Name = "Прочая оргтехника",
                            TranslitName = "prochaya-orgtehnika"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Name = "Сетевые фильтры и удлинители",
                            TranslitName = "setevye-filtry-i-udliniteli"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Name = "Аксессуары для компьютеров",
                            TranslitName = "aksessuary-dlya-kompyuterov"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Name = "Аксессуары и расходные материалы",
                            TranslitName = "aksessuary-i-rashodnye-materialy"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Name = "Измерительные инструменты",
                            TranslitName = "izmeritelnye-instrumenty"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Name = "Спецодежда",
                            TranslitName = "specodejda"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Name = "Электроинструмент",
                            TranslitName = "elektroinstrument"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Name = "Ручной инструмент",
                            TranslitName = "ruchnoi-instrument"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Name = "Сварочное оборудование",
                            TranslitName = "svarochnoe-oborudovanie"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Name = "Бензоинструмент",
                            TranslitName = "benzoinstrument"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Name = "Пневмоинструмент",
                            TranslitName = "pnevmoinstrument"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Name = "Светотехника",
                            TranslitName = "svetotehnika"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Name = "Техника для сада",
                            TranslitName = "tehnika-dlya-sada"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Name = "Игровые приставки",
                            TranslitName = "igrovye-pristavki"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Name = "Игры для приставок",
                            TranslitName = "igry-dlya-pristavok"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Name = "Аксессуары для игровых приставок",
                            TranslitName = "aksessuary-dlya-igrovyh-pristavok"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Name = "Настольные игры",
                            TranslitName = "nastolnye-igry"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Name = "Хозяйственные товары",
                            TranslitName = "hozyaistvennye-tovary"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            Name = "Мультиварки",
                            TranslitName = "multivarki"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Name = "Климатическое оборудование",
                            TranslitName = "klimaticheskoe-oborudovanie"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Name = "Мебель и интерьер",
                            TranslitName = "mebel-i-interer"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Name = "Микроволновые печи",
                            TranslitName = "mikrovolnovye-pechi"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Name = "Пылесосы",
                            TranslitName = "pylesosy"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Name = "Стиральные машины",
                            TranslitName = "stiralnye-mashiny"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Name = "Товары для красоты и здоровья",
                            TranslitName = "tovary-dlya-krasoty-i-zdorovya"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Name = "Товары для кухни",
                            TranslitName = "tovary-dlya-kuhni"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Name = "Утюги и отпариватели",
                            TranslitName = "utyugi-i-otparivateli"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Name = "Чайники и кофеварки",
                            TranslitName = "chainiki-i-kofevarki"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Name = "Холодильники и морозильники",
                            TranslitName = "holodilniki-i-morozilniki"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Name = "Швейные машины",
                            TranslitName = "shveinye-mashiny"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Name = "Бритвы и машинки для стрижки",
                            TranslitName = "britvy-i-mashinki-dlya-strijki"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Name = "Фены и плойки",
                            TranslitName = "feny-i-ploiki"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Name = "Весы",
                            TranslitName = "vesy"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Name = "Электрические плиты",
                            TranslitName = "elektricheskie-plity"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            Name = "Мойки высокого давления",
                            TranslitName = "moiki-vysokogo-davleniya"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Name = "Насосы и компрессоры",
                            TranslitName = "nasosy-i-kompressory"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            Name = "Автомагнитолы",
                            TranslitName = "avtomagnitoly"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Name = "Автомобильные аксессуары и комплектующие",
                            TranslitName = "avtomobilnye-aksessuary-i-komplektuyucshie"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Name = "Автомобильные колонки",
                            TranslitName = "avtomobilnye-kolonki"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            Name = "Автомобильные сабвуферы",
                            TranslitName = "avtomobilnye-sabvufery"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            Name = "Автомобильные усилители",
                            TranslitName = "avtomobilnye-usiliteli"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            Name = "Парктроники и сигнализация",
                            TranslitName = "parktroniki-i-signalizaciya"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            Name = "Видеорегистраторы",
                            TranslitName = "videoregistratory"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 6,
                            Name = "Навигаторы",
                            TranslitName = "navigatory"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 6,
                            Name = "Шины и диски",
                            TranslitName = "shiny-i-diski"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            Name = "Фотоаппараты",
                            TranslitName = "fotoapparaty"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            Name = "Видеокамеры",
                            TranslitName = "videokamery"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            Name = "Аксессуары для фото и видеокамер",
                            TranslitName = "aksessuary-dlya-foto-i-videokamer"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 8,
                            Name = "Зимний спортивный инвентарь",
                            TranslitName = "zimnii-sportivnyi-inventar"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 8,
                            Name = "Металлоискатели",
                            TranslitName = "metalloiskateli"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 8,
                            Name = "Бинокли и оптика",
                            TranslitName = "binokli-i-optika"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            Name = "Водный инвентарь",
                            TranslitName = "vodnyi-inventar"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            Name = "Тату-машинки",
                            TranslitName = "tatumashinki"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 8,
                            Name = "Велосипеды и самокаты",
                            TranslitName = "velosipedy-i-samokaty"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 8,
                            Name = "Пневматика и электрошокеры",
                            TranslitName = "pnevmatika-i-elektroshokery"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 8,
                            Name = "Тренажеры",
                            TranslitName = "trenajery"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 8,
                            Name = "Роликовые и ледовые коньки",
                            TranslitName = "rolikovye-i-ledovye-konki"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            Name = "Туризм",
                            TranslitName = "turizm"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 9,
                            Name = "Канцтовары",
                            TranslitName = "kanctovary"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 9,
                            Name = "Часы",
                            TranslitName = "chasy"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 9,
                            Name = "Кошельки и сумки",
                            TranslitName = "koshelki-i-sumki"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 10,
                            Name = "Музыкальные инструменты",
                            TranslitName = "muzykalnye-instrumenty"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 10,
                            Name = "MP3 плееры",
                            TranslitName = "mp3-pleery"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 10,
                            Name = "Колонки",
                            TranslitName = "kolonki"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 10,
                            Name = "Домашние кинотеатры",
                            TranslitName = "domashnie-kinoteatry"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 10,
                            Name = "Музыкальные центры",
                            TranslitName = "muzykalnye-centry"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 11,
                            Name = "Телевизоры",
                            TranslitName = "televizory"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 11,
                            Name = "Видео",
                            TranslitName = "video"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 11,
                            Name = "Проекторы",
                            TranslitName = "proektory"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 11,
                            Name = "Цифровое телевидение",
                            TranslitName = "cifrovoe-televidenie"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 11,
                            Name = "Аксессуары для ТВ и видео",
                            TranslitName = "aksessuary-dlya-tv-i-video"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 12,
                            Name = "Детские автокресла",
                            TranslitName = "detskie-avtokresla"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 12,
                            Name = "Детские игрушки",
                            TranslitName = "detskie-igrushki"
                        });
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductProductTag");

                    b.HasData(
                        new
                        {
                            ProductsId = 1,
                            TagsId = 3
                        },
                        new
                        {
                            ProductsId = 2,
                            TagsId = 1
                        },
                        new
                        {
                            ProductsId = 2,
                            TagsId = 3
                        },
                        new
                        {
                            ProductsId = 3,
                            TagsId = 4
                        },
                        new
                        {
                            ProductsId = 4,
                            TagsId = 2
                        });
                });

            modelBuilder.Entity("CartProduct", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pobeda.Domain.Entity.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.CategoryTag", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Category", "Category")
                        .WithMany("CategoryTags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Product", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.ProductCharacteristic", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Product", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.SubCategory", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pobeda.Domain.Entity.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Category", b =>
                {
                    b.Navigation("CategoryTags");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Product", b =>
                {
                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
