// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pobeda.DAL.Data;

#nullable disable

namespace Pobeda.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240218204022_RenameProductFilter")]
    partial class RenameProductFilter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pobeda.Domain.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Телефоны"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Компьютерная техника"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Инструмент"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Игры и приставки"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Товары для дома"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Авто"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Фото и видеотехника"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Хобби и отдых"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Личные вещи"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Аудиотехника"
                        },
                        new
                        {
                            Id = 11,
                            Name = "ТВ и видео"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Товары для детей"
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.ProductCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCharacteristics");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В кредит"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Состояние новый"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Состояние хорошее"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Состояние отличное"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Состояние удовлетворительное"
                        });
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Сотовые телефоны"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Умные часы и браслеты"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Наушники для телефонов"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Рации"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Зарядные устройства"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Аксессуары для телефонов"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Системные блоки"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Мониторы"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Моноблоки"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Компьютерные мыши"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Клавиатуры"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Компьютерные гарнитуры и наушники"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Web-камеры"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Планшетные пк"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Электронные книги"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Name = "Принтеры и МФУ"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Name = "Роутеры и модемы"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Name = "Жесткие диски"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Name = "Прочая оргтехника"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Name = "Сетевые фильтры и удлинители"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Name = "Аксессуары для компьютеров"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Name = "Аксессуары и расходные материалы"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Name = "Измерительные инструменты"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Name = "Спецодежда"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Name = "Электроинструмент"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Name = "Ручной инструмент"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Name = "Сварочное оборудование"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Name = "Бензоинструмент"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Name = "Пневмоинструмент"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Name = "Светотехника"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Name = "Техника для сада"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Name = "Игровые приставки"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Name = "Игры для приставок"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Name = "Аксессуары для игровых приставок"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Name = "Настольные игры"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Name = "Хозяйственные товары"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            Name = "Мультиварки"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Name = "Климатическое оборудование"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Name = "Мебель и интерьер"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Name = "Микроволновые печи"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Name = "Пылесосы"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Name = "Стиральные машины"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Name = "Товары для красоты и здоровья"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Name = "Товары для кухни"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Name = "Утюги и отпариватели"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Name = "Чайники и кофеварки"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Name = "Холодильники и морозильники"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Name = "Швейные машины"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Name = "Бритвы и машинки для стрижки"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Name = "Фены и плойки"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Name = "Весы"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Name = "Электрические плиты"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            Name = "Мойки высокого давления"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Name = "Насосы и компрессоры"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            Name = "Автомагнитолы"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Name = "Автомобильные аксессуары и комплектующие"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Name = "Автомобильные колонки"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            Name = "Автомобильные сабвуферы"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            Name = "Автомобильные усилители"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            Name = "Парктроники и сигнализация"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            Name = "Видеорегистраторы"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 6,
                            Name = "Навигаторы"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 6,
                            Name = "Шины и диски"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            Name = "Фотоаппараты"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            Name = "Видеокамеры"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            Name = "Аксессуары для фото и видеокамер"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 8,
                            Name = "Зимний спортивный инвентарь"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 8,
                            Name = "Металлоискатели"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 8,
                            Name = "Бинокли и оптика"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            Name = "Водный инвентарь"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            Name = "Тату-машинки"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 8,
                            Name = "Велосипеды и самокаты"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 8,
                            Name = "Пневматика и электрошокеры"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 8,
                            Name = "Тренажеры"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 8,
                            Name = "Роликовые и ледовые коньки"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            Name = "Туризм"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 9,
                            Name = "Канцтовары"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 9,
                            Name = "Часы"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 9,
                            Name = "Кошельки и сумки"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 10,
                            Name = "Музыкальные инструменты"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 10,
                            Name = "MP3 плееры"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 10,
                            Name = "Колонки"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 10,
                            Name = "Домашние кинотеатры"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 10,
                            Name = "Музыкальные центры"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 11,
                            Name = "Телевизоры"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 11,
                            Name = "Видео"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 11,
                            Name = "Проекторы"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 11,
                            Name = "Цифровое телевидение"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 11,
                            Name = "Аксессуары для ТВ и видео"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 12,
                            Name = "Детские автокресла"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 12,
                            Name = "Детские игрушки"
                        });
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductProductTag");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Product", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.ProductCharacteristic", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Product", "Product")
                        .WithMany("Characteristics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.SubCategory", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductProductTag", b =>
                {
                    b.HasOne("Pobeda.Domain.Entity.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pobeda.Domain.Entity.ProductTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Pobeda.Domain.Entity.Product", b =>
                {
                    b.Navigation("Characteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
